name: Feature Branch CI

on:
  push:
    branches:
      - "feature/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install --file pom.xml

      - name: Run tests
        run: mvn test --file pom.xml
